import type {
  Asset,
  Campaign,
  PromptStructure,
  PromptTemplate,
  Review,
  Shot,
  ShotGeneration,
} from "@/lib/studio/types";
import { composeStructuredPrompt } from "@/lib/utils/prompts";

const launchHeroPrompt: PromptStructure = {
  action: "Founder steps through an illuminated product tunnel and pauses for a hero reveal.",
  camera: "Slow dolly in with a subtle parallax arc ending on a locked medium-wide hero frame.",
  constraints:
    "No warped hands, no floating UI, keep product silhouette consistent, avoid excessive lens flare.",
  dialogueAudioIntent:
    "Low-key cinematic sound design with a single line delivered cleanly to camera.",
  environment: "Premium dark studio with reflective floor, volumetric haze, and branded light strips.",
  lighting: "Directional key with cool rim lights and restrained cyan highlights.",
  mood: "Confident, premium, launch-night anticipation.",
  subject: "Founder in tailored black wardrobe holding the hero product.",
  visualStyle: "Photoreal, polished brand film, restrained luxury tech aesthetic.",
};

const socialMotionPrompt: PromptStructure = {
  action: "Character pivots with the product in hand while interface callouts animate around them.",
  camera: "Controlled handheld-feel push with crisp lock-offs for hook beats.",
  constraints:
    "Preserve facial identity, keep motion readable, avoid rubbery handoffs and noisy backgrounds.",
  dialogueAudioIntent: "Short lip-sync-friendly line with punchy social-native pacing.",
  environment: "Minimal branded room with a practical light wall and product pedestal.",
  lighting: "High-contrast key with practical sources visible in frame.",
  mood: "Sharp, energetic, ad-ready momentum.",
  subject: "Confident creator talent demonstrating the product naturally.",
  visualStyle: "Social-first premium ad spot with clean graphic readability.",
};

const experimentalPrompt: PromptStructure = {
  action:
    "Product fragments reassemble into a surreal hero tableau as the scene expands beyond reality.",
  camera: "Floating crane move that transitions into a wide impossible orbit.",
  constraints: "Keep brand geometry legible, avoid muddy textures, no chaotic transitions.",
  dialogueAudioIntent: "No dialogue, only tonal music bed and atmospheric impact cues.",
  environment: "Abstract black void evolving into a cinematic dream environment.",
  lighting: "High-contrast beams with dramatic practical reflections.",
  mood: "Exploratory, bold, future-facing.",
  subject: "Hero product emerging from fragments and light.",
  visualStyle: "Cinematic experimentation with precise composition and premium polish.",
};

const lumaHeroPrompt: PromptStructure = {
  action:
    "The citrus energy drink can rotates slowly with polished condensation and premium product emphasis.",
  camera: "Macro product camera with slow orbit.",
  constraints: "Avoid warped labels, avoid extra objects, keep branding centered.",
  dialogueAudioIntent: "No spoken dialogue, intense whoosh and impact sound design.",
  environment: "Dark premium reflective studio.",
  lighting: "Moody rim lighting with glossy highlights.",
  mood: "Luxury, modern, crisp.",
  subject: "Sleek citrus energy drink can with visible condensation.",
  visualStyle: "Premium ad cinematic realism.",
};

const lumaLifestylePrompt: PromptStructure = {
  action:
    "A stylish young adult takes a sip from the can and lands a refreshed, confident reaction.",
  camera: "Handheld close-medium ad shot with a subtle push-in.",
  constraints: "Keep hands natural, avoid facial distortion, keep can design readable.",
  dialogueAudioIntent: "Soft ambient city sound, optional upbeat music, no dialogue.",
  environment: "Sunlit rooftop lounge.",
  lighting: "Golden-hour commercial sunlight.",
  mood: "Fresh, aspirational, elevated.",
  subject: "Stylish young adult holding a premium citrus energy drink.",
  visualStyle: "Social ad realism with polished lifestyle cinematography.",
};

export const demoCampaigns: Campaign[] = [
  {
    audience: "Health-conscious adults 24-40 who like sleek premium lifestyle brands",
    brandName: "Luma Drink",
    callToAction: "Shop now",
    clientName: "Internal Demo Client",
    createdAt: "2026-03-19T15:10:00.000Z",
    defaultAspectRatios: ["9:16", "1:1", "16:9"],
    hookAngle: "Luxury energy with clean ingredients",
    id: "cmp_luma_launch",
    name: "Spring Product Launch",
    objective: "Launch a premium sparkling energy drink campaign",
    offer: "New citrus energy drink with clean ingredients",
    slug: "spring-product-launch",
    status: "active",
    targetPlatforms: ["instagram", "tiktok", "youtube-shorts"],
  },
  {
    audience: "Performance marketers and creative directors at fast-moving ecommerce brands.",
    brandName: "Vantage Labs",
    callToAction: "Book a strategy session",
    clientName: "Vantage",
    createdAt: "2026-03-18T16:15:00.000Z",
    defaultAspectRatios: ["16:9", "9:16"],
    hookAngle: "Launch-night premium reveal with polished product authority.",
    id: "cmp_vantage_launch",
    name: "Spring Hero Launch",
    objective:
      "Launch a premium hero campaign that positions the product as polished, cinematic, and high-converting.",
    offer: "Limited launch bundle with strategy bonus.",
    slug: "spring-hero-launch",
    status: "active",
    targetPlatforms: ["YouTube", "Meta", "Landing Page"],
  },
  {
    audience: "Growth leads and founder-operators scanning short-form performance creatives.",
    brandName: "Northstar Commerce",
    callToAction: "Start a free trial",
    clientName: "Northstar",
    createdAt: "2026-03-17T14:05:00.000Z",
    defaultAspectRatios: ["9:16"],
    hookAngle: "UGC-style immediacy with cleaner CTA pacing.",
    id: "cmp_northstar_social",
    name: "UGC Motion Sprint",
    objective:
      "Create repeatable paid-social variants with strong hooks and clearer product motion.",
    offer: "14-day free trial with concierge onboarding.",
    slug: "ugc-motion-sprint",
    status: "in_review",
    targetPlatforms: ["TikTok", "Instagram Reels", "Meta"],
  },
  {
    audience: "Executive buyers evaluating a premium SaaS purchase with a longer sales cycle.",
    brandName: "Atlas Stack",
    callToAction: "Request a live demo",
    clientName: "Atlas",
    createdAt: "2026-03-16T11:40:00.000Z",
    defaultAspectRatios: ["16:9"],
    hookAngle: "High-concept cinematic storytelling for executive buyers.",
    id: "cmp_atlas_pitch",
    name: "Executive Narrative Cut",
    objective:
      "Develop a cinematic explainer with premium polish for outbound, deck embeds, and landing page use.",
    offer: "Enterprise implementation workshop.",
    slug: "executive-narrative-cut",
    status: "draft",
    targetPlatforms: ["LinkedIn", "Landing Page", "Sales Enablement"],
  },
];

export const demoShots: Shot[] = [
  {
    aspectRatio: "9:16",
    campaignId: "cmp_luma_launch",
    createdAt: "2026-03-19T15:22:00.000Z",
    durationSeconds: 6,
    id: "shot_luma_1",
    notes: "Use this as the hero opener for the Luma Drink launch cut.",
    promptStructure: lumaHeroPrompt,
    promptText:
      "A premium macro cinematic product shot of a sleek citrus energy drink can slowly rotating in a dark reflective studio, dramatic rim lighting, glossy condensation, ultra realistic liquid beads, elegant commercial composition, smooth orbit camera move, polished luxury beverage advertisement look",
    purpose: "Premium opening hero shot of the can",
    sceneId: "scene_luma_1",
    sceneNumber: 1,
    shotNumber: 1,
    status: "prompt_ready",
    targetModel: "sora",
    title: "Can Hero Spin",
  },
  {
    aspectRatio: "9:16",
    campaignId: "cmp_luma_launch",
    createdAt: "2026-03-19T15:28:00.000Z",
    durationSeconds: 8,
    id: "shot_luma_2",
    notes: "Good candidate for motion-led social variants once product hero is approved.",
    promptStructure: lumaLifestylePrompt,
    promptText:
      "A stylish young adult on a rooftop lounge at golden hour takes a sip from a premium citrus energy drink and reacts with a refreshed confident expression, subtle camera push-in, natural body motion, polished lifestyle commercial feel, realistic hands and face, premium social ad look",
    purpose: "Human-driven motion shot showing refreshment moment",
    sceneId: "scene_luma_2",
    sceneNumber: 2,
    shotNumber: 1,
    status: "prompt_ready",
    targetModel: "kling",
    title: "Lifestyle Sip",
  },
  {
    aspectRatio: "16:9",
    campaignId: "cmp_vantage_launch",
    createdAt: "2026-03-18T16:25:00.000Z",
    durationSeconds: 8,
    id: "shot_vantage_1",
    notes: "Primary hero opener. Needs premium realism and flawless product silhouette.",
    promptStructure: launchHeroPrompt,
    promptText: composeStructuredPrompt(launchHeroPrompt),
    purpose: "Open the campaign with a hero shot that signals premium quality immediately.",
    sceneId: "scene_vantage_1",
    sceneNumber: 1,
    shotNumber: 1,
    status: "generating",
    targetModel: "sora",
    title: "Hero reveal entrance",
  },
  {
    aspectRatio: "16:9",
    campaignId: "cmp_vantage_launch",
    createdAt: "2026-03-18T16:32:00.000Z",
    durationSeconds: 6,
    id: "shot_vantage_2",
    notes: "Need a cleaner camera lock for editability.",
    promptStructure: {
      ...launchHeroPrompt,
      action:
        "Founder places the product on a pedestal while branded UI light wraps across the frame.",
    },
    promptText: composeStructuredPrompt({
      ...launchHeroPrompt,
      action:
        "Founder places the product on a pedestal while branded UI light wraps across the frame.",
    }),
    purpose: "Bridge from hero reveal into product focus with strong edit points.",
    sceneId: "scene_vantage_1",
    sceneNumber: 1,
    shotNumber: 2,
    status: "reviewed",
    targetModel: "sora",
    title: "Pedestal lockup",
  },
  {
    aspectRatio: "9:16",
    campaignId: "cmp_northstar_social",
    createdAt: "2026-03-17T14:15:00.000Z",
    durationSeconds: 10,
    id: "shot_northstar_1",
    notes: "Lip-sync-safe motion with punchier hand gesture timing.",
    promptStructure: socialMotionPrompt,
    promptText: composeStructuredPrompt(socialMotionPrompt),
    purpose: "Create a fast hook for paid social with crisp character-driven motion.",
    sceneId: "scene_northstar_1",
    sceneNumber: 1,
    shotNumber: 1,
    status: "selected",
    targetModel: "kling",
    title: "UGC hook turn",
  },
  {
    aspectRatio: "9:16",
    campaignId: "cmp_northstar_social",
    createdAt: "2026-03-17T14:28:00.000Z",
    durationSeconds: 9,
    id: "shot_northstar_2",
    notes: "Try a sharper CTA beat at the end for stronger hook strength.",
    promptStructure: {
      ...socialMotionPrompt,
      action: "Talent demonstrates the mobile workflow and lands on a crisp CTA gesture.",
    },
    promptText: composeStructuredPrompt({
      ...socialMotionPrompt,
      action: "Talent demonstrates the mobile workflow and lands on a crisp CTA gesture.",
    }),
    purpose: "Show product usage with controlled motion and stronger CTA clarity.",
    sceneId: "scene_northstar_1",
    sceneNumber: 1,
    shotNumber: 2,
    status: "queued",
    targetModel: "kling",
    title: "Feature handoff",
  },
  {
    aspectRatio: "16:9",
    campaignId: "cmp_atlas_pitch",
    createdAt: "2026-03-16T12:05:00.000Z",
    durationSeconds: 12,
    id: "shot_atlas_1",
    notes:
      "Use this as the exploratory scene to test worldbuilding range before locking brand-safe cuts.",
    promptStructure: experimentalPrompt,
    promptText: composeStructuredPrompt(experimentalPrompt),
    purpose: "Explore a high-concept opener for executive narrative storytelling.",
    sceneId: "scene_atlas_1",
    sceneNumber: 1,
    shotNumber: 1,
    status: "planned",
    targetModel: "higgsfield",
    title: "Abstract product genesis",
  },
];

export const demoShotGenerations: ShotGeneration[] = [
  {
    aspectRatio: "16:9",
    createdAt: "2026-03-18T16:45:00.000Z",
    durationSeconds: 8,
    generationNotes: "Hero variation two with stronger silhouette control.",
    id: "gen_vantage_1",
    integrationMode: "mock",
    outputUrl: "/assets/demo/vantage-hero-v2.mp4",
    progress: null,
    provider: "sora",
    providerMessage: "Sora integration stub ready for real API wiring.",
    providerJobId: "mock-sora-shot_vantage_1",
    providerStatus: "mocked",
    requestPayload: {
      aspectRatio: "16:9",
      durationSeconds: 8,
      promptVersion: "v2",
      shotId: "shot_vantage_1",
    },
    responsePayload: {
      message: "Sora integration stub ready for real API wiring.",
      status: "mocked",
    },
    seed: "hero-seed-01",
    shotId: "shot_vantage_1",
    status: "mocked",
    thumbnailUrl: "/assets/demo/vantage-key-visual.png",
  },
  {
    aspectRatio: "9:16",
    createdAt: "2026-03-17T14:20:00.000Z",
    durationSeconds: 10,
    generationNotes: "Social hook variation with cleaner gesture timing.",
    id: "gen_northstar_1",
    integrationMode: "mock",
    outputUrl: "/assets/demo/northstar-ugc-v4.mp4",
    progress: null,
    provider: "kling",
    providerMessage: "Kling integration stub ready for real API wiring.",
    providerJobId: "mock-kling-shot_northstar_1",
    providerStatus: "mocked",
    requestPayload: {
      aspectRatio: "9:16",
      durationSeconds: 10,
      promptVersion: "v4",
      shotId: "shot_northstar_1",
    },
    responsePayload: {
      message: "Kling integration stub ready for real API wiring.",
      status: "mocked",
    },
    seed: "social-seed-04",
    shotId: "shot_northstar_1",
    status: "mocked",
    thumbnailUrl: "/assets/demo/northstar-ugc-thumb.jpg",
  },
];

export const demoPromptTemplates: PromptTemplate[] = [
  {
    category: "hero",
    createdAt: "2026-03-18T15:00:00.000Z",
    description: "Use for polished launch-night reveal shots.",
    finalTemplate: "Subject: {{subject}}",
    id: "tpl_hero_launch",
    isSystem: true,
    name: "Premium hero launch",
    targetModel: "sora",
  },
  {
    category: "social",
    createdAt: "2026-03-17T13:30:00.000Z",
    description: "Use for fast hook-driven social variants.",
    finalTemplate: "Subject: {{subject}}",
    id: "tpl_social_motion",
    isSystem: true,
    name: "Social motion hook",
    targetModel: "kling",
  },
  {
    category: "exploration",
    createdAt: "2026-03-16T11:30:00.000Z",
    description: "Use for surreal or worldbuilding-first creative exploration.",
    finalTemplate: "Subject: {{subject}}",
    id: "tpl_exploratory_opener",
    isSystem: true,
    name: "Exploratory cinematic opener",
    targetModel: "higgsfield",
  },
  {
    actionTemplate: "{{action}}",
    cameraTemplate: "{{camera}}",
    category: "product",
    constraintsTemplate: "{{constraints}}",
    createdAt: "2026-03-19T15:32:00.000Z",
    description: "For premium product beauty shots.",
    dialogueAudioTemplate: "{{dialogue_audio_intent}}",
    environmentTemplate: "{{environment}}",
    finalTemplate:
      "{{subject}}. {{action}}. {{camera}}. {{environment}}. {{lighting}}. {{mood}}. {{visual_style}}. {{dialogue_audio_intent}}. {{constraints}}.",
    id: "tpl_premium_product_hero",
    isSystem: true,
    lightingTemplate: "{{lighting}}",
    moodTemplate: "{{mood}}",
    name: "Premium Product Hero",
    subjectTemplate: "A premium product shot featuring {{subject}}",
    targetModel: "sora",
    visualStyleTemplate: "{{visual_style}}",
  },
];

export const demoAssets: Asset[] = [
  {
    campaignId: "cmp_vantage_launch",
    createdAt: "2026-03-18T16:22:00.000Z",
    fileName: "vantage-key-visual.png",
    fileUrl: "/assets/demo/vantage-key-visual.png",
    id: "asset_vantage_ref_1",
    metadataJson: { aspect_ratio: "16:9", palette: "violet-cyan", resolution: "2048x1152" },
    mimeType: "image/png",
    shotId: "shot_vantage_1",
    source: "upload",
    tags: ["hero", "reference"],
    type: "reference_image",
  },
  {
    campaignId: "cmp_vantage_launch",
    createdAt: "2026-03-18T16:50:00.000Z",
    durationSeconds: 8,
    fileName: "vantage-hero-v2.mp4",
    fileUrl: "/assets/demo/vantage-hero-v2.mp4",
    generationId: "gen_vantage_1",
    height: 1080,
    id: "asset_vantage_gen_1",
    metadataJson: { duration_seconds: 8, version: "v2", width: 1920 },
    mimeType: "video/mp4",
    shotId: "shot_vantage_1",
    source: "generated",
    tags: ["hero", "select"],
    type: "generated_video",
    width: 1920,
  },
  {
    campaignId: "cmp_northstar_social",
    createdAt: "2026-03-17T14:18:00.000Z",
    fileName: "northstar-ugc-thumb.jpg",
    fileUrl: "/assets/demo/northstar-ugc-thumb.jpg",
    id: "asset_northstar_thumb_1",
    metadataJson: { aspect_ratio: "9:16", frame: "opening-hook" },
    mimeType: "image/jpeg",
    shotId: "shot_northstar_1",
    source: "generated",
    tags: ["thumbnail", "social"],
    type: "thumbnail",
  },
  {
    campaignId: "cmp_northstar_social",
    createdAt: "2026-03-17T14:22:00.000Z",
    durationSeconds: 10,
    fileName: "northstar-ugc-v4.mp4",
    fileUrl: "/assets/demo/northstar-ugc-v4.mp4",
    generationId: "gen_northstar_1",
    height: 1920,
    id: "asset_northstar_gen_1",
    metadataJson: { duration_seconds: 10, version: "v4", width: 1080 },
    mimeType: "video/mp4",
    shotId: "shot_northstar_1",
    source: "generated",
    tags: ["social", "selected"],
    type: "generated_video",
    width: 1080,
  },
  {
    campaignId: "cmp_atlas_pitch",
    createdAt: "2026-03-16T11:55:00.000Z",
    fileName: "atlas-brand-logo.svg",
    fileUrl: "/assets/demo/atlas-brand-logo.svg",
    id: "asset_atlas_logo_1",
    metadataJson: { background: "transparent", usage: "endcard" },
    mimeType: "image/svg+xml",
    shotId: null,
    source: "upload",
    tags: ["brand"],
    type: "logo",
  },
  {
    campaignId: "cmp_atlas_pitch",
    createdAt: "2026-03-16T12:08:00.000Z",
    fileName: "atlas-character-sheet.png",
    fileUrl: "/assets/demo/atlas-character-sheet.png",
    id: "asset_atlas_character_1",
    metadataJson: { notes: "Executive wardrobe references", pages: 1 },
    mimeType: "image/png",
    shotId: "shot_atlas_1",
    source: "upload",
    tags: ["reference", "character"],
    type: "character_sheet",
  },
];

export const demoReviews: Review[] = [
  {
    assetId: "asset_vantage_gen_1",
    createdAt: "2026-03-18T17:05:00.000Z",
    decision: "selected",
    id: "review_vantage_1",
    notes:
      "Excellent brand fit and lighting. Needs a cleaner hand transition in the opening beat.",
    reviewerName: "Creative Ops",
    scoreBrandFit: 9,
    scoreEditability: 8,
    scoreHookStrength: 8,
    scoreMotionQuality: 8,
    scorePromptFidelity: 9,
    scoreRealism: 9,
    selectedBoolean: true,
    shotId: "shot_vantage_1",
  },
  {
    assetId: "asset_northstar_gen_1",
    createdAt: "2026-03-17T14:42:00.000Z",
    decision: "selected",
    id: "review_northstar_1",
    notes: "The hook works fast, but we need stronger CTA timing for the back half.",
    reviewerName: "Performance Creative",
    scoreBrandFit: 8,
    scoreEditability: 9,
    scoreHookStrength: 7,
    scoreMotionQuality: 8,
    scorePromptFidelity: 8,
    scoreRealism: 8,
    selectedBoolean: true,
    shotId: "shot_northstar_1",
  },
  {
    assetId: "asset_northstar_thumb_1",
    createdAt: "2026-03-17T14:30:00.000Z",
    decision: "rejected",
    id: "review_northstar_2",
    notes: "Good thumbnail frame, but the facial expression needs more urgency.",
    reviewerName: "Performance Creative",
    scoreBrandFit: 7,
    scoreEditability: 8,
    scoreHookStrength: 6,
    scoreMotionQuality: 7,
    scorePromptFidelity: 7,
    scoreRealism: 7,
    selectedBoolean: false,
    shotId: "shot_northstar_1",
  },
];
